source 'https://api.berkshelf.com'

cookbook 'apt', git: 'git://github.com/opscode-cookbooks/apt.git'
cookbook 'ark', git: 'git://github.com/opscode-cookbooks/ark.git'
cookbook 'bluepill', git: 'git://github.com/opscode-cookbooks/bluepill.git'
cookbook 'build-essential', git: 'git://github.com/opscode-cookbooks/build-essential.git'
cookbook 'java', git: 'git://github.com/opscode-cookbooks/java.git'
cookbook 'monit',  git: 'git://github.com/apsoto/monit.git'
cookbook 'ohai',  git: 'git://github.com/opscode-cookbooks/ohai.git'
cookbook 'python',  git: 'git://github.com/poise/python.git'
cookbook 'rsyslog', git: 'git://github.com/opscode-cookbooks/rsyslog.git'
cookbook 'windows',  git: 'git://github.com/opscode-cookbooks/windows.git'
cookbook 'yum', git: 'git://github.com/opscode-cookbooks/yum.git'
cookbook 'yum-epel', git: 'git://github.com/opscode-cookbooks/yum-epel.git'
cookbook 'elasticsearch', git: 'git://github.com/elasticsearch/cookbook-elasticsearch.git', 
cookbook 'mongodb', git: 'git://github.com/edelight/chef-mongodb'
